### PR TITLE
feat: add onboarding UI screens with Swiper.js carousel

### PR DESCRIPTION
**Pull request by anurag6569201**
This PR introduces the onboarding UI screen using the Swiper.js carousel library. The onboarding experience includes a series of slides designed to showcase the GC event.

Dependencies Added:
Swiper.js: A modern library for implementing carousels.
Installed via npm install swiper

Screenshots
Screenshot 2024-12-19 at 12 46 10 PM
Screenshot 2024-12-19 at 12 46 30 PM

### CODE REVIEW

**Comment by zakhaev26** [comment]
can the card glow effect be removed ?

**Comment by anurag6569201** [comment]
> can the card glow effect be removed ?

ya sure
Screenshot 2024-12-19 at 2 36 00 PM

**Comment by ujsquared** [comment]
@anurag6569201 check for npm run lint once

**Comment by ujsquared** [comment]
@anurag6569201 is this linted? npm run lint?

**Comment by ujsquared** [comment]
I have added a type-check script to package.json 
For checking typesafety next time, use `npm run type-check`

**Comment by ujsquared** [comment]
@anurag6569201 check the changes, useful for future

**Pull request merged**
